#include "robot_controller.h"
#include "app_callbacks.h"

#include <gtk/gtk.h>

int connect_all_signals(const char *ui_filename)
{
    GtkApplication *app;
    GtkBuilder *builder;
    GObject *obj;

    /* Parse UI file generated by glade */
    if((builder = gtk_builder_new_from_file(ui_filename)) == NULL)
    {
        /* If parse failed, it will return NULL, let user know */
        g_printerr("Error loading xml file: %s\n", ui_filename);
        return -1;
    }
    
    /* Get every relevant object from the builder file */
    /* Connect X button to gtk_main_quit */
    obj = gtk_builder_get_object(builder, "window");
    g_signal_connect(obj, "destroy", G_CALLBACK(gtk_main_quit), NULL);

    /* Connect run temporary server button to react function */
    obj = gtk_builder_get_object(builder, "btn_run_temporary_diag_server");
    g_signal_connect(obj, "clicked", G_CALLBACK(react_btn_run_temporary_diag_server), NULL);
    
    /* Connect address field to robot_controller file */
    obj = gtk_builder_get_object(builder, "txt_server_ip");
    add_txt_server_ip_entry((GtkEntry *)obj);
    
    /* Connect port field to robot_controller file */
    obj = gtk_builder_get_object(builder, "txt_server_port");
    add_txt_server_port_entry((GtkEntry *)obj);

    /* Connect status buffer to robot_controller file */
    obj = gtk_builder_get_object(builder, "txtbuf_robot_controller_status");
    add_txt_controller_status_buffer((GtkTextBuffer *)obj);

    return 0;
}
