name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Build the project and ensure it compiles
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: ./build.sh
  
    # Once the project is built, upload the binary 
    - name: 'put together'
      run: cp ./build/MainApp.ui .; cp ./build/PenguinTuner .; cp ./backend/lib/libPenguin_Backend.so .
    - name: tar
      run: tar -cvf PenguinTuner.tar MainApp.ui libPenguin_Backend.so PenguinTuner    
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: PenguinTuner
        path: PenguinTuner.tar   
    
      
