name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Build the project and ensure it compiles
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: 'build and package'
      run: ./package.sh
  
    # Once the project is built, upload the deb package   
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: PenguinTuner
        path: build/PenguinTuner*.deb
    
      
