name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Build the project and ensure it compiles
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: ./build.sh
  
  # Once the project is built, upload the binary 
  upload:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: tar
        run: tar -cvf PenguinTuner.tar ./build/MainApp.ui ./build/PenguinTuner
        
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: PenguinTuner
          path: PenguinTuner.tar   
    
      
