name: C/C++ CI

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  # Build the project and ensure it compiles
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure.sh
    - name: 'build and package'
      run: ./package.sh
  
    # Once the project is built, upload the deb package   
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: PenguinTuner
        path: build/PenguinTuner*.deb

  release:
    runs-on: ubuntu-latest
    needs: [build]
    # Release the version if it includes a tag that starts with "v"
    if: success() && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Import GPG key to sign package release
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        
      - name: Download previous job artifact
        uses: actions/download-artifact@v2
        with:
          name: PenguinTuner
      
      - name: Create Pacakges & Packages.gz files
        run: dpkg-scanpackages --multiversion . > Packages; gzip -k -f Packages
        
      - name: Create Release, Release.gpg, and InRelease files
        run: apt-ftparchive release . > Release; gpg --default-key "coryness@tytan.rocks" -abs -o - Release > Release.gpg; gpg --default-key "coryness@tytan.rocks" --clearsign -o - Release > InRelease
        
      - name: Check directory
        run: ls -R
