name: Checkout and Build
# This workflow is to ensure that anybody can configure and build this project using only configure and build scripts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-native-linux:
    runs-on: ubuntu-18.04
    container:
      image: debian:bookworm
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: ./configure.sh
      - name: build
        run: ./build.sh

  build-native-macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: ./configure.sh
      - name: build
        run: ./build.sh
        
  build-otherarch:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: armv6
          - arch: armv7
          - arch: aarch64

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: tytanrock/run-on-arch-action@master
      name: build and configure
      with:
        arch: ${{ matrix.arch }}
        distro: bookworm
        run: |
          ./configure.sh
          ./build.sh
