name: Release Update

on:
  push:
    tags:
      - v* # On pushing a tag following format v*
jobs:
  # Get the latest artifacts and push them to the gh-pages branch
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
      - uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R


